application: gombi-net
version: 1
runtime: go
api_version: go1

handlers:
- url: /straph/.*
  script: _go_app
- url: /door
  script: _go_app
- url: /api/.*
  script: _go_app
- url: /
  static_files: ../webapp/build/es6prod/index.html
  upload: ../webapp/build/es6prod/index.html
- url: /rsc
  static_dir: ../webapp/rsc/
- url: /node_modules
  static_dir: ../webapp/build/es6prod/node_modules/
- url: /jsgen
  static_dir: ../webapp/build/es6prod/jsgen/
